### ISSUE TITLE
Small question on the FibaroRingCam.py script

### ISSUE THREAD

**Issue by galadril** [joepv/fibaro#1]
Hi,

Thanks for this script in the first place.. Ill be looking into changing it to integrate with Domoticz Home Automation system.

But I was wondering, do you need the paid subscription for snapshots to work??

Mark

**Comment by joepv** [comment]
Hi Mark, you need a paid subscription. I use the generated video (.mp4) files to make a snapshot.
This causes a delay with getting the snapshot, but at the moment this is the best you get.

**Comment by galadril** [comment]
Ok thanks.
